import { createFileRoute } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";

import { supabaseBrowser } from "#/lib/supabaseBrowser";

export const Route = createFileRoute("/erp/new-vendor")({
  component: VendorInsertPage,
});

type VendorInsertResult = {
  vendor_id: number;
  vendor_name: string;
  vendor_address: string;
};

function VendorInsertPage() {
  const [loading, setLoading] = useState(false);
  const [vendorName, setVendorName] = useState("");
  const [vendorAddress, setVendorAddress] = useState("");
  const [message, setMessage] = useState<{ type: "success" | "error"; text: string } | null>(null);
  const [lastInserted, setLastInserted] = useState<VendorInsertResult | null>(null);

  const handleInsert = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setLoading(true);
    setMessage(null);
    setLastInserted(null);

    const trimmedName = vendorName.trim();
    const trimmedAddress = vendorAddress.trim();

    if (!trimmedName || !trimmedAddress) {
      setMessage({ type: "error", text: "Please fill in vendor name and vendor address." });
      setLoading(false);
      return;
    }

    if (!supabaseBrowser) {
      setMessage({
        type: "error",
        text: "Supabase is not configured. Check VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.",
      });
      setLoading(false);
      return;
    }

    try {
      const { data, error } = await supabaseBrowser
        .from("vendor")
        .insert([
          {
            vendor_name: trimmedName,
            vendor_address: trimmedAddress,
          },
        ])
        .select("vendor_id, vendor_name, vendor_address")
        .single();

      if (error) {
        console.error(error);
        setMessage({ type: "error", text: `Error: ${error.message}` });
      } else {
        console.log(data);
        setLastInserted(data);
        setVendorName("");
        setVendorAddress("");
        setMessage({
          type: "success",
          text: `Vendor created successfully (ID: ${data.vendor_id}).`,
        });
      }
    } catch (err) {
      console.error(err);
      setMessage({ type: "error", text: "Unexpected error while inserting vendor." });
    }

    setLoading(false);
  };

  return (
    <div className="min-h-screen bg-slate-950 px-4 py-10 text-slate-100">
      <div className="mx-auto max-w-2xl rounded-2xl border border-white/10 bg-white/5 p-6 shadow-[0_18px_70px_rgba(15,23,42,0.55)] backdrop-blur">
        <h1 className="mb-2 text-2xl font-semibold">New Vendor</h1>
        <p className="mb-6 text-sm text-slate-300">
          Insert a new row into the <code>vendor</code> table. <code>vendor_id</code> is
          auto-generated by Supabase.
        </p>

        <form onSubmit={handleInsert} className="space-y-4">
          <label className="flex flex-col gap-2 text-sm">
            <span className="text-slate-300">Vendor Name</span>
            <input
              value={vendorName}
              onChange={(e) => setVendorName(e.target.value)}
              placeholder="Acme Corp"
              className="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-3 text-sm text-slate-100 outline-none placeholder:text-slate-400"
            />
          </label>

          <label className="flex flex-col gap-2 text-sm">
            <span className="text-slate-300">Vendor Address</span>
            <textarea
              value={vendorAddress}
              onChange={(e) => setVendorAddress(e.target.value)}
              rows={3}
              placeholder="123 Main St, Springfield, IL 62701"
              className="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-3 text-sm text-slate-100 outline-none placeholder:text-slate-400"
            />
          </label>

          <div className="flex justify-end">
            <button
              type="submit"
              disabled={loading}
              className="inline-flex items-center justify-center rounded-lg bg-gradient-to-r from-cyan-400 to-blue-500 px-5 py-3 text-sm font-semibold text-slate-900 shadow-lg shadow-cyan-500/30 transition hover:opacity-95 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {loading ? "Saving…" : "Create Vendor"}
            </button>
          </div>
        </form>

        {message && (
          <div
            className={`mt-4 rounded-lg px-3 py-2 text-sm ${
              message.type === "success"
                ? "border border-emerald-400/40 bg-emerald-400/10 text-emerald-100"
                : "border border-red-400/40 bg-red-400/10 text-red-100"
            }`}
          >
            {message.text}
          </div>
        )}

        {lastInserted && (
          <div className="mt-4 rounded-lg border border-cyan-300/30 bg-cyan-300/10 p-3 text-sm text-cyan-100">
            <p className="font-semibold">Inserted row</p>
            <p>ID: {lastInserted.vendor_id}</p>
            <p>Name: {lastInserted.vendor_name}</p>
            <p>Address: {lastInserted.vendor_address}</p>
          </div>
        )}
      </div>
    </div>
  );
}
