/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupabaseTestRouteImport } from './routes/supabase-test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvoiceNewRouteImport } from './routes/invoice/new'
import { Route as InvoiceIdRouteImport } from './routes/invoice/$id'
import { Route as ErpLoginRouteImport } from './routes/erp/login'
import { Route as ErpInvoiceRouteImport } from './routes/erp/invoice'
import { Route as ErpDashboardRouteImport } from './routes/erp/dashboard'

const SupabaseTestRoute = SupabaseTestRouteImport.update({
  id: '/supabase-test',
  path: '/supabase-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceNewRoute = InvoiceNewRouteImport.update({
  id: '/invoice/new',
  path: '/invoice/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ErpLoginRoute = ErpLoginRouteImport.update({
  id: '/erp/login',
  path: '/erp/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErpInvoiceRoute = ErpInvoiceRouteImport.update({
  id: '/erp/invoice',
  path: '/erp/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ErpDashboardRoute = ErpDashboardRouteImport.update({
  id: '/erp/dashboard',
  path: '/erp/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/supabase-test': typeof SupabaseTestRoute
  '/erp/dashboard': typeof ErpDashboardRoute
  '/erp/invoice': typeof ErpInvoiceRoute
  '/erp/login': typeof ErpLoginRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/invoice/new': typeof InvoiceNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/supabase-test': typeof SupabaseTestRoute
  '/erp/dashboard': typeof ErpDashboardRoute
  '/erp/invoice': typeof ErpInvoiceRoute
  '/erp/login': typeof ErpLoginRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/invoice/new': typeof InvoiceNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/supabase-test': typeof SupabaseTestRoute
  '/erp/dashboard': typeof ErpDashboardRoute
  '/erp/invoice': typeof ErpInvoiceRoute
  '/erp/login': typeof ErpLoginRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/invoice/new': typeof InvoiceNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/supabase-test'
    | '/erp/dashboard'
    | '/erp/invoice'
    | '/erp/login'
    | '/invoice/$id'
    | '/invoice/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/supabase-test'
    | '/erp/dashboard'
    | '/erp/invoice'
    | '/erp/login'
    | '/invoice/$id'
    | '/invoice/new'
  id:
    | '__root__'
    | '/'
    | '/supabase-test'
    | '/erp/dashboard'
    | '/erp/invoice'
    | '/erp/login'
    | '/invoice/$id'
    | '/invoice/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SupabaseTestRoute: typeof SupabaseTestRoute
  ErpDashboardRoute: typeof ErpDashboardRoute
  ErpInvoiceRoute: typeof ErpInvoiceRoute
  ErpLoginRoute: typeof ErpLoginRoute
  InvoiceIdRoute: typeof InvoiceIdRoute
  InvoiceNewRoute: typeof InvoiceNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supabase-test': {
      id: '/supabase-test'
      path: '/supabase-test'
      fullPath: '/supabase-test'
      preLoaderRoute: typeof SupabaseTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/new': {
      id: '/invoice/new'
      path: '/invoice/new'
      fullPath: '/invoice/new'
      preLoaderRoute: typeof InvoiceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erp/login': {
      id: '/erp/login'
      path: '/erp/login'
      fullPath: '/erp/login'
      preLoaderRoute: typeof ErpLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erp/invoice': {
      id: '/erp/invoice'
      path: '/erp/invoice'
      fullPath: '/erp/invoice'
      preLoaderRoute: typeof ErpInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erp/dashboard': {
      id: '/erp/dashboard'
      path: '/erp/dashboard'
      fullPath: '/erp/dashboard'
      preLoaderRoute: typeof ErpDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SupabaseTestRoute: SupabaseTestRoute,
  ErpDashboardRoute: ErpDashboardRoute,
  ErpInvoiceRoute: ErpInvoiceRoute,
  ErpLoginRoute: ErpLoginRoute,
  InvoiceIdRoute: InvoiceIdRoute,
  InvoiceNewRoute: InvoiceNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
