/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupabaseTestRouteImport } from './routes/supabase-test'
import { Route as IndexRouteImport } from './routes/index'

const SupabaseTestRoute = SupabaseTestRouteImport.update({
  id: '/supabase-test',
  path: '/supabase-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/supabase-test': typeof SupabaseTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/supabase-test': typeof SupabaseTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/supabase-test': typeof SupabaseTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/supabase-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/supabase-test'
  id: '__root__' | '/' | '/supabase-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SupabaseTestRoute: typeof SupabaseTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supabase-test': {
      id: '/supabase-test'
      path: '/supabase-test'
      fullPath: '/supabase-test'
      preLoaderRoute: typeof SupabaseTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SupabaseTestRoute: SupabaseTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
